spring:
  application:
    name: "Community-Playlists-Service"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydatabase"
    username: "myuser"
    password: "mypassword"
logging:
  level:
    org.flywaydb: DEBUG